### ISSUE TITLE
[emerg] 1#1: [lua] init_by_lua:14: fatal error when loading the root module

### ISSUE THREAD

**Issue by ptyagii** [tnscorcoran/soap-apicast#2]
Getting "fatal error" when running command " docker run --name apicast --rm -p 80:8080 -v /root/soap-apicast/configuration.lua:/opt/app-root/src/src/configuration.lua -e THREESCALE_PORTAL_ENDPOINT=https://b0b1b87af6bb38bf329cd87f24611505bf1f421be994f85737@user-admin.3scale.net -e APICAST_LOG_LEVEL=debug registry.access.redhat.com/3scale-amp20/apicast-gateway"; however; it works when running without the custom file. 

Output of the logs: 

[root@node2 ~]# docker run --name apicast --rm -p 80:8080 -v /root/soap-apicast/configuration.lua:/opt/app-root/src/src/configuration.lua -e THREESCALE_PORTAL_ENDPOINT=https://b0b1b87af6bb38bf329cd87f24611505bf1f421be994f85737@user-admin.3scale.net -e APICAST_LOG_LEVEL=debug registry.access.redhat.com/3scale-amp20/apicast-gateway
Aug 29 20:41:26 dnsmasq[9]: started, version 2.76 cachesize 1000
 ....
Aug 29 20:41:26 dnsmasq[9]: reading /etc/resolv.conf
Aug 29 20:41:26 dnsmasq[9]: using nameserver nameserver#0
Aug 29 20`:41:26 dnsmasq[9]: using nameserver 10.10.10.10#53
Aug 29 20:41:26 dnsmasq[9]: cleared cache
2017/08/29 20:41:27 [debug] 1#1: [lua] resolver.lua:73: parse_nameservers(): /etc/resolv.conf:
Generated by NetworkManager
...
nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
nameserver 10.74.250.14
...
...
2017/08/29 20:41:27 [warn] 1#1: [lua] module.lua:20: prequire(): cannot open apicast: No such file or directory, stack traceback:
	/opt/app-root/src/src/module.lua:20: in function 'prequire'
	/opt/app-root/src/src/module.lua:30: in main chunk
	[C]: in function 'require'
	init_by_lua:11: in main chunk
2017/08/29 20:41:27 [emerg] 1#1: [lua] init_by_lua:14: fatal error when loading the root module

**Comment by kevprice83** [comment]
@tnscorcoran any ideas on the above?

**Comment by tnscorcoran** [comment]
@ptyagii I tested again on my Mac and on AWS and it worked ok.

A couple of possibilities I can think of
1) Have you definitely changed directory in your terminal to where configuration.lua is?
2) configuration.lua is unchanged from the one in this repo?
If you verify these, can you send me the commands you use up to and including docker run?

**Comment by tnscorcoran** [comment]
Also @ptyagii, can you confirm the 3scale account you want to use is user-admin.3scale.net? This is an old 3scale account belonging to someone else. Looks incorrect?

**Comment by ptyagii** [comment]
@tnscorcoran 
>> Have you definitely changed directory in your terminal to where configuration.lua is?
yes

>> configuration.lua is unchanged from the one in this repo?
I did not modify anything in "configuration.lua" file. 

>> can you confirm the 3scale account you want to use is user-admin.3scale.net?  
My account is "ptyagii-admin.3scale.net" .  

I tested it on my virtual machine;if you want its details, let me know.

**Comment by tnscorcoran** [comment]
@ptyagii is it publicly available where I could log in and take a look?

**Comment by ptyagii** [comment]
@tnscorcoran  closing this issue as running with "--security-opt label:disable" option did the trick and disabled selinux for this container only. 

docker run --security-opt label:disable --name apicast --rm -p 8080:8080 -v $(pwd)/configuration.lua:/opt/app-root/src/src/configuration.lua -e THREESCALE_PORTAL_ENDPOINT=https://b0b1b87af6bb38bf329cd87f24611505bf1f421be994f8573751da1bf130796d@ptyagii-admin.3scale.net -e APICAST_LOG_LEVEL=debug registry.access.redhat.com/3scale-amp20/apicast-gateway

Thanks.
